---
deployment:
  tasks:
    - export BRANCH=$(git branch --show-current)
    - export ENV=$([ "$BRANCH" = "main" ] && echo production || echo staging)

    # backend
    - export BACKEND_DEPLOYPATH=/home/paje6276/apps/${ENV}/backend/
    - /bin/mkdir -p $BACKEND_DEPLOYPATH
    - /bin/cp -R backend/. $BACKEND_DEPLOYPATH
    - source /home/paje6276/nodevenv/apps/${ENV}/backend/24/bin/activate && cd $BACKEND_DEPLOYPATH && npm install && npm run build
    - /bin/mkdir -p $BACKEND_DEPLOYPATH/tmp
    - /bin/touch $BACKEND_DEPLOYPATH/tmp/restart.txt

    # pwa
    - export PWA_DEPLOYPATH=/home/paje6276/apps/${ENV}/pwa/
    - /bin/mkdir -p $PWA_DEPLOYPATH
    - /bin/cp -R pwa/. $PWA_DEPLOYPATH
    - source /home/paje6276/nodevenv/apps/${ENV}/pwa/22/bin/activate && cd $PWA_DEPLOYPATH && PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 npm install && npm run build
    - /bin/cp -R $PWA_DEPLOYPATH/.next/static $PWA_DEPLOYPATH/.next/standalone/pwa/.next/static
    - /bin/cp -R $PWA_DEPLOYPATH/public $PWA_DEPLOYPATH/.next/standalone/pwa/public
    - /bin/mkdir -p $PWA_DEPLOYPATH/tmp
    - /bin/touch $PWA_DEPLOYPATH/tmp/restart.txt
