packages:
  - "pwa"
  - "backend"
  - "landing"
  - "packages/*"

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

allowBuilds:
  esbuild: true
  sharp: true
  "@prisma/engines": true
  "@prisma/client": true
  prisma: true
