name: Test SSH connectivity

on:
  workflow_dispatch:

jobs:
  test-ssh:
    name: test-ssh
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "connected ok"
            whoami
            pwd
